#!/usr/bin/env bash
# find-or-create-autofix-pr.sh
# Finds an existing open autofix PR for an issue, or creates a new one.
# Prevents duplicate PRs when /fix is triggered multiple times.
#
# Usage:
#   find-or-create-autofix-pr.sh <repo> <issue-number> <branch-name> <title> <body-file> <GH_TOKEN>
#
# Outputs (to GITHUB_OUTPUT format):
#   pr_number=<N>
#   pr_url=<url>
#   action=created|reused

set -euo pipefail

REPO="$1"
ISSUE_NUM="$2"
BRANCH_NAME="$3"
TITLE="$4"
BODY_FILE="$5"
GH_TOKEN="$6"

# Check for existing open autofix PR for this issue
EXISTING_PR=$(gh pr list \
  --head "autofix/issue-${ISSUE_NUM}" \
  --state open \
  --json number,url \
  --jq ".[0] | {number: .number, url: .url}" 2>/dev/null || echo "null")

PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.number // empty')
PR_URL=$(echo "$EXISTING_PR" | jq -r '.url // empty')

if [ -n "$PR_NUMBER" ]; then
  # PR exists — update its body and push branch
  echo "Reusing existing PR #${PR_NUMBER}"

  # Update PR body if body file exists
  if [ -f "$BODY_FILE" ]; then
    gh pr edit "$PR_NUMBER" --body-file "$BODY_FILE" --repo "$REPO" 2>/dev/null || true
  fi

  echo "pr_number=${PR_NUMBER}"
  echo "pr_url=${PR_URL}"
  echo "action=reused"
else
  # No existing PR — create one
  echo "Creating new autofix PR for issue #${ISSUE_NUM}"

  BODY="## Fixes #${ISSUE_NUM}

"
  if [ -f "$BODY_FILE" ]; then
    BODY="${BODY}$(cat "$BODY_FILE")

"
  fi
  BODY="${BODY}---
*Auto-generated by fix-audit-issue workflow*"

  PR_URL=$(gh pr create \
    --base main \
    --head "$BRANCH_NAME" \
    --title "$TITLE" \
    --body "$(echo -e "$BODY")" \
    --repo "$REPO")

  PR_NUMBER=$(echo "$PR_URL" | grep -oP '/pull/\K[0-9]+' || echo "")

  echo "pr_number=${PR_NUMBER}"
  echo "pr_url=${PR_URL}"
  echo "action=created"
fi
